### ISSUE TITLE
Use this repo as a testbed for trying the PDD bot

### ISSUE THREAD

**Issue by frou** [frou/GoFeather#4]

**Comment by 0pdd** [comment]
@frou the puzzle [#5](https://github.com/frou/GoFeather/issues/5) is still not solved.

**Comment by 0pdd** [comment]
@frou the puzzle [#6](https://github.com/frou/GoFeather/issues/6) is still not solved; solved: [#5](https://github.com/frou/GoFeather/issues/5).

**Comment by 0pdd** [comment]
@frou the puzzle [#7](https://github.com/frou/GoFeather/issues/7) is still not solved; solved: [#5](https://github.com/frou/GoFeather/issues/5), [#6](https://github.com/frou/GoFeather/issues/6).

**Comment by 0pdd** [comment]
@frou all 3 puzzles are solved here: [#5](https://github.com/frou/GoFeather/issues/5), [#6](https://github.com/frou/GoFeather/issues/6), [#7](https://github.com/frou/GoFeather/issues/7).
